import math 

IMAGE_SIZE = 128
PATCH_SIZE = 64
EPSILON = 2
PERCENT_SAMPLING = 1/2
HEAD_LR = 0.01
#####################
NUM_PATCHES = IMAGE_SIZE//PATCH_SIZE
TOTAL_NUM_PATCHES = NUM_PATCHES**2
MAX_INNER_ITERATION = math.ceil(1/PERCENT_SAMPLING)
LATENT_DIM = 384

if EPSILON > MAX_INNER_ITERATION:
    print("Error")
    exit()